### ISSUE TITLE
[WIP] Community strategy development

### ISSUE THREAD

**Issue by cassgvp** [alan-turing-institute/environment-and-sustainability-gc-community#2]
### Summary Sentence

Capturing the development of the [E&S Community strategy](https://github.com/alan-turing-institute/environment-and-sustainability-gc-community/blob/main/docs/strategy/community-strategy.md)

#### Roadmap:
- [ ] Diagnosis
    - [ ] Invites sent for Community member 121 interviews
        - [x] Delivery/Ops (n=2)
        - [ ] E&S Leadership (n=2)
        - [x] Researchers (n=3-5)
        - [x] Turing Fellows (n=3-5)
        - [x] Networked and Sustained Participants (n=2)
        - [ ] Open call on Turing E&S Slack (n=2-4)
        - [ ] Open call on TTW E&S Slack (n=1-2)
        - [ ] Partners: ABRDN; NERC; UKCEH; BAS; OCF; Met Office
    - [ ] Interviews completed - [WIP notes archived on github](https://github.com/alan-turing-institute/environment-and-sustainability-gc-community/blob/main/meeting-notes/meeting-community-strategy-rcm-121s.md); [live on hackmd](https://hackmd.io/@turing-es/HyQyA10mA/edit)
        - [ ] Delivery/Ops (n=2)
        - [ ] E&S Leadership (n=2)
        - [x] Researchers (n=3-5)
        - [ ] Turing Fellow (n=3-5)
        - [ ] Networked and Sustained Participants (n=2)
        - [ ] Open call on Turing E&S Slack (n=2-4)
        - [ ] Open call on TTW E&S Slack (n=1-2)
        - [ ] Partners: ABRDN; NERC; UKCEH; BAS; OCF; Met Office
    - [ ] Review of stakeholder map
    - [ ] Analysis of baseline data - [WIP notes archived on github](https://github.com/alan-turing-institute/environment-and-sustainability-gc-community/blob/main/meeting-notes/meeting-community-strategy-rcm-analysis.md); [live on hackmd](https://hackmd.io/@turing-es/BJvESG18C)
- [ ] Design
    - [ ] What do we want to change from above? What is our vision for the community
    - [ ] How will we measure change?
    - [ ] How will we implement change?
- [ ] Execute
    - [ ] High-level initiatives
    - [ ] Timeline for delivery

### Who can help?

TPS RCM Strategy group, E&S delivery group. 

Conversations happening on Turing Slack #env-sustain-community-strategy

---

### Update after the issue was opened

[Add details]
